Update project settings and setup

diff --git a/repository-setup/setup-machine b/repository-setup/setup-machine
--- a/repository-setup/setup-machine
+++ b/repository-setup/setup-machine
@@ -8,109 +8,135 @@ echo "------------------------------------ VARIABLES ---------------------------
 # Establish the base repository reference directory
 THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 REPOSITORY_DIR="$( dirname $THIS_DIR )"
-REPOSITORY_CONFIG="$THIS_DIR/repository-config"
-
+REPOSITORY_CONFIG_FILE="$REPOSITORY_DIR/repository-setup/repository-config.ini"
 
 echo "THIS_DIR=$THIS_DIR"
 echo "REPOSITORY_DIR=$REPOSITORY_DIR"
+echo "REPOSITORY_CONFIG_FILE=$REPOSITORY_CONFIG_FILE"
+
+if [ ! -f $REPOSITORY_CONFIG_FILE ]; then
+    echo "ERROR: Repository config file not found."
+    echo "    location=$REPOSITORY_CONFIG_FILE"
+    exit 1
+fi
+
+# Setup our local directory
+CACHE_DIR="$REPOSITORY_DIR/.cache"
+if [ ! -d $CACHE_DIR ]; then
+    mkdir $CACHE_DIR
+fi
+
+INITIALIZED_FILE="$CACHE_DIR/initialized"
+REPOSITORY_CONFIG_INI_FILE="$RESPOSITORY_DIR/repository-setup/repository-config.ini"
+VIRTUAL_ENV_DIR="$REPOSITORY_DIR/.venv"
+VIRTUAL_ENV_BIN_DIR="$VIRTUAL_ENV_DIR/bin"
+
+ENV_FILE="$REPOSITORY_DIR/.env"
+if [ ! -f $ENV_FILE ]; then
+    echo "ERROR: Development environment file not found. Did you run the 'repository-setup' script."
+    echo "    location=$ENV_FILE"
+    exit 1
+fi
+
+echo "ENV_FILE=$ENV_FILE"
+
+CUSTOM_CLI_ALIAS=""
+CUSTOM_CLI_ENTRY_SCRIPT=""
+PROJECT_NAME=""
+PYTHON_VERSION=""
+
+source $ENV_FILE
+source (grep --color=never -E "^[\s]*[A-Za-z_]+[A-Za-z_0-9]*=" "$REPOSITORY_CONFIG_INI_FILE")
+
+# The PYTHON_VERSION can be pinned in the development environment config
+if [ -z "$PYTHON_VERSION" ]
+then
+    echo "ERROR: The 'PYTHON_VERSION' variable should be set in the development environment file."
+    echo "    location=$ENV_FILE"
+    exit 1
+fi
+
+echo "CUSTOM_CLI_ALIAS=$CUSTOM_CLI_ALIAS"
+echo "CUSTOM_CLI_ENTRY_SCRIPT=$CUSTOM_CLI_ENTRY_SCRIPT"
+echo "PROJECT_NAME=$PROJECT_NAME"
+echo "PYTHON_VERSION=$PYTHON_VERSION"
+echo "VIRTUAL_ENV_DIR=$VIRTUAL_ENV_DIR"
+echo "VIRTUAL_ENV_BIN_DIR=$VIRTUAL_ENV_BIN_DIR"
 
 echo "---------------------------------------------------------------------------------------"
 
+
 # -------------------------------------------------------------------------------------------
-#                                 System Package Installation
+#                                 Perform Reset if Required
 # -------------------------------------------------------------------------------------------
-echo
-echo
-echo "-------------------------------- SYSTEM PACKAGES --------------------------------------"
+if [ "$1" == "reset" ]; then
+    rm -fr $VIRTUAL_ENV_DIR
+    rm -f $INITIALIZED_FILE
+fi
 
-function ensure_apt_dependencies() {
-    echo "APT INSTALLING: $1"
-    read -a dependency_list <<< $1 # Split the dependency string on spaces into a bash array
-
-    for nxt_dep in "${dependency_list[@]}"
-    do
-        PCHK_OUTPUT="$(dpkg -s $nxt_dep)";
-        if [ "$(echo $?)" != 0 ]; then
-            echo "System Dependency ($nxt_dep): being installed"
-            sudo apt install $nxt_dep
-        else
-            echo "System Dependency ($nxt_dep): already installed"
-        fi
-    done
-}
-
-function ensure_pip_dependencies() {
-    echo "APT INSTALLING: $1"
-    read -a dependency_list <<< $1 # Split the dependency string on spaces into a bash array
-
-    for nxt_dep in "${dependency_list[@]}"
-    do
-        PCHK_OUTPUT="$(pip3 list | grep $nxt_dep)";
-        if [ "$(echo $?)" != 0 ]; then
-            echo "System Dependency ($nxt_dep): being installed"
-            sudo pip3 install $nxt_dep
-        else
-            echo "System Dependency ($nxt_dep): already installed"
-        fi
-    done
-}
-
-function ensure_pipx_dependencies() {
+# -------------------------------------------------------------------------------------------
+#                                 Virtual Environment Commanline Customization
+# -------------------------------------------------------------------------------------------
+function customize_activate_script() {
     
-    echo "PIPX INSTALLING: $1"
-    read -a dependency_list <<< $1 # Split the dependency string on spaces into a bash array
+    echo "# ================ Development Environment Customizations ================"
+    echo ""  >> $ACTIVATE_SCRIPT
+    echo "if [ -f $ENV_FILE ]" >> $ACTIVATE_SCRIPT
+    echo "then" >> $ACTIVATE_SCRIPT
+    echo "    set -a" >> $ACTIVATE_SCRIPT
+    echo "    source $ENV_FILE" >> $ACTIVATE_SCRIPT
+    echo "    set +a" >> $ACTIVATE_SCRIPT
+    echo "fi" >> $ACTIVATE_SCRIPT
+    echo "" >> $ACTIVATE_SCRIPT
 
-    for nxt_dep in "${dependency_list[@]}"
-    do
-        PCHK_OUTPUT="$(pipx list | grep \"package $nxt_dep\")";
-        if [ "$(echo $?)" != 0 ]; then
-            echo "PipX Dependency ($nxt_dep): being installed"
-            sudo apt install $nxt_dep
-        else
-            echo "PipX Dependency ($nxt_dep): already installed"
+    # Check for custom commandline additions
+    if [ ! -z "$CUSTOM_CLI_ALIAS" ] || [ ! -z "$CUSTOM_CLI_ENTRY_SCRIPT" ];
+    then
+        if [ ! -z "$CUSTOM_CLI_ALIAS" ] && [ ! -z "$CUSTOM_CLI_ENTRY_SCRIPT" ];
+        then
+            echo "# Create an alias for the $CUSTOM_CLI_ALIAS command" >> $ACTIVATE_SCRIPT
+            echo "function $CUSTOM_CLI_ALIAS () {" >> $ACTIVATE_SCRIPT
+            echo "    \"$VIRTUAL_ENV_BIN_DIR/python3\" \"$CUSTOM_CLI_ENTRY_SCRIPT\" \$@ " >> $ACTIVATE_SCRIPT
+            echo "}"  >> $ACTIVATE_SCRIPT
+            echo "export -f $CUSTOM_CLI_ALIAS"  >> $ACTIVATE_SCRIPT
+            echo ""  >> $ACTIVATE_SCRIPT
         fi
-    done
+    else
+        echo "To add a custom commandline, you must set both 'CUSTOM_CLI_ALIAS' and 'CUSTOM_CLI_ENTRY_SCRIPT'"
+        exit 1
+    fi
+    
 }
 
-function ensure_system_dependencies () {
-    dependencies=$1
-    # Split off the system dependency install base on system type Linux, MacOS, Windows, etc
-
-    # For now we only support Linux
-    ensure_apt_dependencies "$dependencies"
-}
-
-function ensure_pip_system_dependencies () {
-    dependencies=$1
-    # Split off the system dependency install base on system type Linux, MacOS, Windows, etc
-
-    # For now we only support Linux
-    ensure_pip_dependencies "$dependencies"
-}
-
-function ensure_pipx_system_dependencies () {
-    dependencies=$1
-    # Split off the system dependency install base on system type Linux, MacOS, Windows, etc
-
-    # For now we only support Linux
-    ensure_pipx_dependencies "$dependencies"
-}
-
-# Run the dependency checks on the system
-echo "BASE DEPENDENCIES:"
-APT_BASE_DEPENDENCIES="build-essential python3 python3-dev python3-setuptools python3-pip"
-ensure_system_dependencies "$APT_BASE_DEPENDENCIES"
+# -------------------------------------------------------------------------------------------
+#                                 Create the Virtual Environment
+# -------------------------------------------------------------------------------------------
 echo
-
-echo "PIP SYSTEM DEPENDENCIES"
-PIP_SYSTEM_DEPENDENCIES=""
-ensure_pip_system_dependencies "$PIP_SYSTEM_DEPENDENCIES"
 echo
+echo "---------------------------- VIRTUAL ENVIRONMENT CREATION -----------------------------"
+if [ ! -f $INITIALIZED_FILE ]; then
+
+    pushd $REPOSITORY_DIR
+
+    if [ ! -f $VIRTUAL_ENV_DIR/bin/activate ]; then
+        
+        poetry env use $PYTHON_VERSION
+    else
+        echo "ERROR: Unable to create or find the python virtual environment"
+        exit 1
+    fi
+
+    poetry update --no-cache
+
+    popd
+
+    customize_activate_script
+
+    touch $INITIALIZED_FILE
+
+else
+    echo "Virtual environment already intialized..."
+
+fi
+
 echo "---------------------------------------------------------------------------------------"
-
-echo "PIPX DEPENDENCIES"
-PIPX_DEPENDENCIES="poetry"
-ensure_pipx_system_dependencies "$PIPX_DEPENDENCIES"
-echo
-echo "---------------------------------------------------------------------------------------"
-
